[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
enum_dispatch = "0.3.13"
num-traits = "0.2.19"
once_cell = "1.19.0"
rand = { version = "0.8.5", features = ["small_rng"] }
