name: Test Rust project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check --all
      - name: Check compilation
        run: cargo check --all
      - name: Run tests
        run: cargo test --all --release
